### ISSUE TITLE
List index out of range when scraping for all songs from an artist

### ISSUE THREAD

**Issue by psevdoname** [jameswenzel/pylyrics3#5]
```
Traceback (most recent call last):
  File "lyricwik.py", line 14, in <module>
    taylor = pylyrics3.get_artist_lyrics('bob dylan', albums = False)
  File "C:\Users\Artem\Anaconda3\lib\site-packages\pylyrics3.py", line 47, in get_artist_lyrics
    title = self.__parse_song_title(url)
  File "C:\Users\Artem\Anaconda3\lib\site-packages\pylyrics3.py", line 206, in __parse_song_title
    return PyLyrics3._decode_lyricwiki(url.split(':')[2])
IndexError: list index out of range
```
This is the output from the programme, that makes use of the get_artist_lyrics(). The same happens for Taylor Swift, Madonna and MIley Cyrus queries, however it works just fine for Bon Iver, Led zeppelin and some other ones. What might be the problem?

**Comment by emo-eth** [comment]
Hey, good catch. This has to do with cover songs - the original artist gets caught by the CSS selector which doesn't have a `:` in the URL.
In figuring that out, I caught another bug, namely that the script picks up all songs from compilation albums rather than just the songs by the specified artist. I should have a fix for that, too, shortly.

**Comment by emo-eth** [comment]
Version 1.0.4 should fix this, with the caveat that `pylyrics3` doesn't know that Miley Cyrus and Hannah Montanna are the same person - you'll have to manually combine those `dict`s, unfortunately.
I'm having trouble uploading to `pip` at the moment, so you'll have to clone the repo and run `python setup.py install` manually in the meantime.

**Comment by emo-eth** [comment]
I still need to upload this to pip.
